"""fix relationship

Revision ID: b8d46687547d
Revises: 5195a9c0ff94
Create Date: 2025-05-26 14:46:23.519712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d46687547d'
down_revision: Union[str, None] = '5195a9c0ff94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
